name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Run test suite

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install built-fast/gh-shellcheck
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh extension install built-fast/gh-shellcheck

      - name: Run shellcheck
        run: |
          gh shellcheck

      - name: Install shfmt
        run: |
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get install -y shfmt

      - name: Run shfmt
        run: |
          shfmt -d -i 2 -sr -ci .
